// design-sync build input — produces a single self-contained stylesheet for the
// importable bundle (cfg.cssEntry → ds-bundle/_ds_bundle.css).
//
// Why this exists: @philemon/ui ships its CSS as global.css, which @imports
// ./tokens.css and ./components.css relatively. The design-sync converter copies
// cssEntry verbatim into _ds_bundle.css at the bundle ROOT, where those relative
// @imports would 404 — every design built with the DS would render unstyled.
// So we inline the three files into one, and prepend the Geist Mono webfont the
// host app loads from Google Fonts (so designs render in the real brand font;
// validate reports this as [FONT_REMOTE], informational).
//
// Pure fs, no deps. Re-run via cfg.buildCmd before the converter on every sync;
// output (packages/ui/dist/) is gitignored and regenerated.

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const srcDir = join(repoRoot, 'packages', 'ui', 'src');
const outFile = join(repoRoot, 'packages', 'ui', 'dist', 'philemon-ui.css');

const read = (f) => readFileSync(join(srcDir, f), 'utf8');

// Geist Mono — same family/weights the host app loads in its index.html.
const FONT_IMPORT =
  "@import url('https://fonts.googleapis.com/css2?family=Geist+Mono:wght@400;500;600&display=swap');";

const tokens = read('tokens.css');
const components = read('components.css');
// global.css's leading @import lines pull in tokens/components — strip them
// (already inlined above) and keep the base element styles.
const globalBase = read('global.css').replace(/^\s*@import\s+[^;]+;\s*$/gm, '').trimStart();

const combined = [
  FONT_IMPORT,
  '/* @philemon/ui — bundled stylesheet (generated by .design-sync/build-css.mjs) */',
  '/* tokens.css */',
  tokens,
  '/* components.css */',
  components,
  '/* global.css (base element styles) */',
  globalBase,
].join('\n\n');

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, combined);
console.error(`wrote ${outFile} (${(combined.length / 1024).toFixed(1)} KB)`);
